Bump rails from 8.1.2.1 to 8.1.3 (#708)
Bumps [rails](https://github.com/rails/rails) from 8.1.2.1 to 8.1.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">rails's
releases</a>.</em></p>
<blockquote>
<h2>8.1.3</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Fix <code>JSONGemCoderEncoder</code> to correctly serialize custom
object hash keys.</p>
<p>When hash keys are custom objects whose <code>as_json</code> returns
a Hash,
the encoder now calls <code>to_s</code> on the original key object
instead of
on the <code>as_json</code> result.</p>
<p>Before:
hash = {CustomKey.new(123) =&gt; &quot;value&quot;}
hash.to_json  # =&gt; {&quot;{:id=&gt;123}&quot;:&quot;value&quot;}</p>
<p>After:
hash.to_json  # =&gt; {&quot;custom_123&quot;:&quot;value&quot;}</p>
<p><em>Dan Sharp</em></p>
</li>
<li>
<p>Fix inflections to better handle overlapping acronyms.</p>
<pre lang="ruby"><code>ActiveSupport::Inflector.inflections(:en) do
|inflect|
  inflect.acronym &quot;USD&quot;
  inflect.acronym &quot;USDC&quot;
end
<p>&quot;USDC&quot;.underscore # =&gt; &quot;usdc&quot;<br />
</code></pre></p>
<p><em>Said Kaldybaev</em></p>
</li>
<li>
<p>Silence Dalli 4.0+ warning when using
<code>ActiveSupport::Cache::MemCacheStore</code>.</p>
<p><em>zzak</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>
<p>Fix Ruby 4.0 delegator warning when calling inspect on
attributes.</p>
<p><em>Hammad Khan</em></p>
</li>
<li>
<p>Fix <code>NoMethodError</code> when deserialising
<code>Type::Integer</code> objects marshalled under Rails 8.0.</p>
<p>The performance optimisation that replaced <code>@range</code> with
<code>@max</code>/<code>@min</code>
broke Marshal compatibility. Objects serialised under 8.0 (with
<code>@range</code>)
and deserialised under 8.1 (expecting
<code>@max</code>/<code>@min</code>) would crash with
<code>undefined method '&lt;=' for nil</code> because
<code>Marshal.load</code> restores instance
variables without calling <code>initialize</code>.</p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/fa8f0812160665bff083a089d2bb2fc1817ea03e"><code>fa8f081</code></a>
Preparing for 8.1.3 release</li>
<li><a
href="https://github.com/rails/rails/commit/63cef3de3bd88d5973837ea268dc710e7dbf7b8e"><code>63cef3d</code></a>
Merge branch '8-1-sec' into 8-1-stable</li>
<li><a
href="https://github.com/rails/rails/commit/174eeb87fe8bb8e30171ba3af28fc66b65217811"><code>174eeb8</code></a>
Update trilogy</li>
<li><a
href="https://github.com/rails/rails/commit/e4499055867156dd5f85186e60b899b5bc0a42bd"><code>e449905</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/57022">#57022</a>
from byroot/sobrinho-main</li>
<li><a
href="https://github.com/rails/rails/commit/7d8eeea98f1b2a1ad136b2281475404d7e9e2c1a"><code>7d8eeea</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/56977">#56977</a>
from hschne/26-03-fix-ignore-virtual-tables</li>
<li><a
href="https://github.com/rails/rails/commit/148e4d8f7a2498e031cca8da8486fc4909ca91a1"><code>148e4d8</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/56970">#56970</a>
from nicolasva/fix_spatia_lite</li>
<li><a
href="https://github.com/rails/rails/commit/e9884dc9ab71eeb71174b48d9b48b1a2e311b583"><code>e9884dc</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/56965">#56965</a>
from rosa/restore-previous-instrumenter-async-block...</li>
<li><a
href="https://github.com/rails/rails/commit/004eb65f43ab44f78113e5345e5ff289db67fe7f"><code>004eb65</code></a>
Restore previous instrumenter after execute_or_skip</li>
<li><a
href="https://github.com/rails/rails/commit/b8b23c09a8f3a0e1933bac7a2f81915064a1e990"><code>b8b23c0</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/56932">#56932</a>
from eglitobias/fix-dbconsole-notimplemented-message</li>
<li><a
href="https://github.com/rails/rails/commit/2250b1658ddb3c468821bc76a96c3d83f7a49617"><code>2250b16</code></a>
Merge pull request <a
href="https://redirect.github.com/rails/rails/issues/56951">#56951</a>
from r-plus/patch-1</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v8.1.2.1...v8.1.3">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=rails&package-manager=bundler&previous-version=8.1.2.1&new-version=8.1.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>